from .base import *

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_BROWSER_XSS_FILTER = True

CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")

SIMPLE_JWT = {
    **SIMPLE_JWT,
    "ALGORITHM": "RS256",
    "SIGNING_KEY": os.environ["JWT_PRIVATE_KEY"].replace("\\n", "\n"),
    "VERIFYING_KEY": os.environ["JWT_PUBLIC_KEY"].replace("\\n", "\n"),
}
