# Generated by Django 6.0.7 on 2026-08-10 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
            },
        ),
    ]
